[package]
name = "bump_future"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.16.0"
crossbeam-queue = "0.3.11"
once_cell = "1.20.2"
sptr = "0.3.2"
tokio = { version = "1.40.0", features = ["rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.40.0", features = ["full"] }
